num_tasks: 3000
num_devices: 200
simulation_horizon_s: 600 # total time horizon (seconds)


mean_task_size_kb: 450
std_task_size_kb: 50


device_cpu_hz: 1.0e9 # 1 GHz
fog_cpu_hz: 2.0e10  # 20 GHz
cloud_cpu_hz: 4.0e10 # 40 GHz


cycles_per_byte: 100
p_tx: 0.5 # transmission power (W)
energy_per_cycle: 1.0e-9 # Joules per cycle


fog_workers: 10
cloud_workers: 5


initial_weights:
  w_local: 0.7
  w_offload: 0.3


round_size: 100
learning_rate: 0.1

topology_path: "Data/topology.json"             # مسیر فایل توپولوژی که فرستادی
default_link_bw_bps: 1000000000            # 1e9 bits/s
device_access_bw_bytes_per_s: 40000000     # 40e6 bytes/s (40 MB/s)
default_rtt_s: 0.005                       # 5 ms per link baseline